apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.30
        ports:
        - containerPort: 5775   # UDP accept: jaeger-agent
        - containerPort: 6831   # UDP accept: jaeger-agent
        - containerPort: 6832   # UDP accept: jaeger-agent
        - containerPort: 5778   # HTTP serve: jaeger-agent
        - containerPort: 16686  # HTTP serve: query service UI
        - containerPort: 14268  # HTTP accept: jaeger-collector
        - containerPort: 14250  # gRPC accept: jaeger-collector
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"