apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - ../grafana/base
  - ../prometheus/base
  - ../tempo/base
  - ../loki/base
  - ../promtail/base
  - ../alloy/base

namespace: monitoring
