apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  api.yaml: |
    otelUrl: "http://tempo.monitoring.svc.cluster.local:4317"
    prometheusUrl: "http://prometheus-server.monitoring.svc.cluster.local:9090"
