apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: plfiorini/otel-test-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9464
              name: metrics
          volumeMounts:
            - name: api-config-volume
              mountPath: /config/api.yaml
              subPath: api.yaml
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: PORT
              value: "3000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger.monitoring.svc.cluster.local:4317"
            #- name: OTEL_EXPORTER_OTLP_ENDPOINT
            #  value: "http://jaeger.monitoring.svc.cluster.local:4318/v1/traces"
            - name: PROMETHEUS_PORT
              value: "9464"
      volumes:
        - name: api-config-volume
          configMap:
            name: api-config
