apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 9464
      targetPort: metrics
      name: metrics
  type: ClusterIP
