apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          image: otel/opentelemetry-collector:latest
          ports:
            - containerPort: 55678
            - containerPort: 4317
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: opentelemetry-collector-config