http:
  host: localhost
  port: 8000
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]
    allow_credentials: true

logger:
  level: debug # debug, info, warn, error, dpanic, panic, fatal
  encoding: json # json or console
  #encoding: console
  outputPaths: [stdout] # e.g., [stdout, logs/app.log]
  errorOutputPaths: [stderr]

otel:
  enabled: true
  #endpoint: "http://localhost:4317"
  #protocol: "grpc" # http or grpc
  endpoint: "http://localhost:4318"
  protocol: "http" # http or grpc
  insecure: true # set to true to disable TLS
