apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: otel-test
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
