adminUser: admin
adminPassword: admin

service:
  enabled: true
  type: LoadBalancer

persistence:
  type: pvc
  enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:9090
      isDefault: true

    - name: Tempo
      type: tempo
      url: http://tempo.monitoring.svc.cluster.local:16686
