tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  persistence:
    enabled: true
    size: 10Gi

# Enable Tempo Query frontend for easier integration with Grafana
tempoQuery:
  enabled: true
