apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    prometheus.remote_write "local" {
      endpoint {
        url = "http://mimir.monitoring.svc.cluster.local:9009/api/v1/push"
      }
    }

    loki.write "local" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

    otelcol.exporter.otlp "local" {
      client {
        endpoint = "tempo.monitoring.svc.cluster.local:4317"
      }
    }

    prometheus.scrape "static" {
      forward_to = [
        prometheus.remote_write.local.receiver,
      ]
      targets = [
        {
          "__address__" = "prometheus.monitoring.svc.cluster.local:9090",
        },
      ]
    }
