apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    prometheus.remote_write "local" {
      endpoint {
        url = "http://mimir:9009/api/v1/push"
      }
    }

    loki.write "local" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }

    otelcol.exporter.otlp "local" {
      client {
        endpoint = "tempo:4317"
      }
    }

    prometheus.scrape "static" {
      forward_to = [
        prometheus.remote_write.local.receiver,
      ]
      targets = [
        {
          "__address__" = "prometheus:9090",
        },
      ]
    }
