apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:latest
          ports:
            - containerPort: 9009
              name: grpc
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: alloy-data
              mountPath: /data
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: alloy-data
          emptyDir: {}
