apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
    - port: 9009
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: alloy
  type: ClusterIP
