apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
    - name: Alloy
      type: prometheus
      url: http://alloy:8080/prometheus
      access: proxy
    - name: Tempo
      type: tempo
      url: http://tempo:3100
      access: proxy
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: 'prometheus'
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      jsonData:
        derivedFields:
          - datasourceUid: Tempo
            matcherRegex: "traceID=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"
