apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemonset.yaml
  - configmap.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml

namespace: monitoring
