apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m
      complete_block_timeout: 30m

    compactor:
      compaction:
        block_retention: 168h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo
        wal:
          path: /tmp/tempo/wal

    overrides:
      metrics_generator_processors: 
        - service-graphs
        - span-metrics
