apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - port: 3100
      name: tempo
      targetPort: tempo
    - port: 9411
      name: zipkin
      targetPort: zipkin
    - port: 4317
      name: otlp-grpc
      targetPort: otlp-grpc
    - port: 4318
      name: otlp-http
      targetPort: otlp-http
    - port: 14268
      name: jaeger-http
      targetPort: jaeger-http
  type: ClusterIP
